import type { Metadata } from "next";
import "./globals.css";
import {  AppContextProvider } from "@/context/AppContext";


export const metadata: Metadata = {
  title: "TASC",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppContextProvider>
        {children}
        </AppContextProvider>
      </body>
    </html>
  );
}
