import type { Metadata } from "next";
import "./globals.css";
import {  AppContextProvider } from "@/context/AppContext";
import Footer from "./Components/Footer";
import Navbar from "./Components/Navbar";
import { Toaster } from "react-hot-toast";


export const metadata: Metadata = {
  title: "TASC",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppContextProvider>
          <Toaster/>
        {children}
        <Footer/>
        </AppContextProvider>
      </body>
    </html>
  );
}
